services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "8080:${PORT}"
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - redis

  redis:
    build:
      context: ../redis/
      dockerfile: Dockerfile
    ports:
      - "${REDIS_PORT_OUTER}:${REDIS_PORT_INNER}"


