[config]
default_to_workspace = false

[env]
HOST = "0.0.0.0"
PORT = 8080
REDIS_PORT_OUTER = 6379
REDIS_PORT_INNER = 6379

[tasks.set-env-docker.env]
REDIS_HOST = "redis"
REDIS_PORT = "${REDIS_PORT_INNER}"

[tasks.set-env-local.env]
REDIS_HOST = "localhost"
REDIS_PORT = "${REDIS_PORT_OUTER}"

[tasks.before-build]
run_task = [
    { name = [
        "compose-up-redis",
    ]}
]

[tasks.compose-build-app]
extend = "set-env-local"
command = "docker"
args = [
    "compose", "build", "app",
    "--build-arg", "BUILDKIT_INLINE_CACHE=1", "${@}"
]

[tasks.run-in-docker]
extend = "set-env-docker"
dependencies = ["before-build"]

[tasks.check]
extend = "set-env-local"
dependencies = ["before-build"]
command = "cargo"
args = ["check"]

[tasks.watch]
extend = "set-env-local"
dependencies = ["before-build"]
run_task = [{ name = ["fmt", "clippy", "test"] }]
watch = true

[tasks.fmt]
extend = "set-env-local"
command = "cargo"
args = ["fmt", "--all", "${@}"]

[tasks.clippy]
extend = "set-env-local"
command = "cargo"
args = ["clippy", "--all", "--all-targets", "${@}"]

[tasks.test]
extend = "set-env-local"
install_crate = { crate_name = "cargo-nextest", binary = "cargo", test_arg = [
    "nextest", "--help",
]}
command = "cargo"
args = [
    "nextest", "run", "--workspace",
    "--status-level", "all", "--test-threads=1"
]

[tasks.clippy-ci]
dependencies = ["before-build"]
run_task = "clippy"

[tasks.test-ci]
dependencies = ["before-build"]
run_task = "test"

[tasks.compose]
extend = "set-env-docker"
command = "docker"
args = ["compose", "${@}"]

[tasks.compose-up-redis]
extend = "set-env-docker"
command = "docker"
args = ["compose", "up", "-d", "redis"]

[tasks.compose-down]
extend = "set-env-docker"
command = "docker"
args = ["compose", "down"]

[tasks.compose-remove]
extend = "set-env-docker"
command = "docker"
args = ["compose", "down", "-v"]